INSERT INTO questions (id, text, "order", active) VALUES
(1, 'Do you own multiple rental properties?', 1, 1),
(2, 'Do you struggle with tracking tenant payments?', 2, 1),
(3, 'Do you currently use Excel to manage your properties?', 3, 1),
(4, 'Is responding to tenant inquiries time-consuming?', 4, 1),
(5, 'Do you find it difficult to keep track of property maintenance?', 5, 1),
(6, 'Are you concerned about complying with German rental laws?', 6, 1),
(7, 'Do you manage your rental properties remotely?', 7, 1),
(8, 'Do you have issues with regular financial reporting?', 8, 1),
(9, 'Would you like to automate tenant communications?', 9, 1),
(10, 'Do you have trouble managing utility bills?', 10, 1),
(11, 'Are you manually creating lease agreements?', 11, 1),
(12, 'Do you have a system for tenant screening?', 12, 1),
(13, 'Are you facing issues with property vacancy rates?', 13, 1),
(14, 'Do you struggle with tax documentation for your properties?', 14, 1),
(15, 'Would you benefit from automated payment reminders?', 15, 1),
(16, 'Do you have a system for handling maintenance requests?', 16, 1),
(17, 'Are you interested in analyzing your property performance data?', 17, 1),
(18, 'Do you find bank statement reconciliation tedious?', 18, 1),
(19, 'Would you like to reduce administrative time spent on property management?', 19, 1),
(20, 'Are you looking for better ways to manage property documentation?', 20, 1);