name = "pmanagement"

main = "out/main.js"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

[env.production]
vars = { NODE_ENV = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "landlord-db"
database_id = "${DATABASE_ID}"
migrations_dir = "migrations"
migrations_table = "drizzle_migrations"

[[env.production.routes]]
pattern = "immo.busqandote.com/api*"
zone_id = "${ZONE_ID}"