name: D1 Database Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/d1/**'
      - 'shared/schema-d1.ts'
      - '.github/workflows/d1-migrations.yml'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: true
        default: 'Manual database migration run'

jobs:
  migrate:
    name: Run D1 Migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate D1 migrations
        run: node generate-d1-schema.js

      - name: Run D1 migrations
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          NODE_ENV: production
        run: node run-d1-migrations.js