name: Database Migrations

on:
  push:
    branches: [ main ]
    paths:
      - 'migrations/**'
      - 'run-migrations.js'
      - '.github/workflows/migrations.yml'
  # Manual trigger
  workflow_dispatch:

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run database migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: production
        run: node run-migrations.js